# Generated by Django 3.2.15 on 2024-01-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='descrition',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
    ]
