# Generated by Django 3.2.15 on 2024-01-06 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_book_descrition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='descrition',
            new_name='description',
        ),
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
